import hi from "../../assets/bình dương.jpg";
import hello from "../../assets/đồng nai.jpg";
import hehe from "../../assets/hà nội.jpg";

export const mockData = [
  {
    id: 'e8e616e0-d894-4936-a3f5-391682ee794c',
    title: "Phân khúc căn hộ tại Hà Nội 'đón sóng' bất động sản năm 2024",
    summary: "Thị trường bất động sản tại Hà Nội đang hồi phục rõ nét, đặc biệt là phân khúc căn hộ.",
    content: "<p>Thị trường bất động sản tại Hà Nội năm 2024 ghi nhận sự phục hồi mạnh mẽ sau thời gian dài trầm lắng. Đặc biệt, phân khúc căn hộ đang trở thành tâm điểm thu hút dòng tiền đầu tư...</p><p>Các dự án căn hộ tại các quận trung tâm như Cầu Giấy, Đống Đa, Ba Đình được người mua quan tâm...</p>",
    author: "Nguyễn Văn A",
    published_at: '2023-12-29T08:54:00+07:00',
    tags: ["BấtĐộngSản", "HàNội", "CănHộ"],
    images: [
      { url: hi },
      { url: hello },
      { url: hehe },
    ],
    videos: [
      { url: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4' },
    ],
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440000',
    title: 'Thị trường bất động sản Hà Nội: Ảo giá, ảo giao dịch',
    summary: "Giá rao bán bất động sản tại Hà Nội tăng mạnh, đặc biệt là phân khúc chung cư, nhưng giao dịch thực tế không nhiều.",
    content: "<p>Hiện tượng 'ngáo giá' đang trở thành vấn đề nổi cộm tại thị trường bất động sản Hà Nội...</p>",
    author: "Trần Thị B",
    published_at: '2024-03-01T08:00:00+07:00',
    tags: ["BấtĐộngSản", "HàNội", "ChungCư"],
  },
  {
    id: '28f69273-7825-4ce5-af65-034dd404ca6c',
    title: 'Tâm điểm mới của bất động sản Hà Nội hấp dẫn giới đầu tư',
    summary: "Khu vực Đông Bắc Hà Nội trở thành điểm đến tiềm năng của thị trường bất động sản.",
    content: "<p>Khu vực Đông Bắc Hà Nội, đặc biệt là các quận như Long Biên và Gia Lâm, đang trở thành tâm điểm mới...</p>",
    author: "Lê Văn C",
    published_at: '2024-07-15T09:00:00+07:00',
    tags: ["BấtĐộngSản", "HàNội", "ĐầuTư"],
    images: [
      { url: hehe },
    ],
  },
  {
    id: 'a0955a25-b9e2-4426-b37d-b63330f64f7a',
    title: 'Hà Nội ghi nhận hơn 52 nghìn giao dịch bất động sản nửa đầu năm 2024',
    summary: "Thị trường bất động sản Hà Nội sôi động trở lại với 52 nghìn giao dịch trong nửa đầu năm 2024.",
    content: "<p>Nửa đầu năm 2024, thị trường bất động sản Hà Nội ghi nhận sự sôi động với hơn 52 nghìn giao dịch...</p>",
    author: "Phạm Thị D",
    published_at: '2024-07-10T08:00:00+07:00',
    tags: ["BấtĐộngSản", "HàNội", "GiaoDịch"],
  },
  {
    id: 'b1c2d3e4-f5a6-4b7c-8d9e-0f1234567890',
    title: 'Thị trường bất động sản nửa đầu năm 2024: điểm nóng phía Tây Hà Nội',
    summary: "Phía Tây Hà Nội tiếp tục là điểm nóng của thị trường bất động sản.",
    content: "<p>Phía Tây Hà Nội, bao gồm các quận như Nam Từ Liêm và Hà Đông, tiếp tục là khu vực dẫn đầu...</p>",
    author: "Nguyễn Văn E",
    published_at: '2024-07-29T08:00:00+07:00',
    tags: ["BấtĐộngSản", "HàNội", "PhíaTây"],
    images: [
      { url: hehe },
    ],
  },
  {
    id: 'c2d3e4f5-a6b7-4c8d-9e0f-1234567890ab',
    title: 'Kỳ vọng có mức giá phù hợp cho thị trường bất động sản Hà Nội',
    summary: "Các chuyên gia kỳ vọng thị trường bất động sản Hà Nội sẽ có mức giá phù hợp hơn.",
    content: "<p>Thị trường bất động sản Hà Nội đang đối mặt với bài toán giá cả...</p>",
    author: "Trần Thị F",
    published_at: '2024-07-15T09:00:00+07:00',
    tags: ["BấtĐộngSản", "HàNội", "NhàỞXãHội"],
  },
  {
    id: 'd3e4f5a6-b7c8-4d9e-0f12-34567890abcd',
    title: "Phân khúc cao cấp tiếp tục 'dẫn dắt' thị trường bất động sản Hà Nội",
    summary: "Phân khúc căn hộ cao cấp tiếp tục dẫn dắt thị trường bất động sản Hà Nội.",
    content: "<p>Phân khúc căn hộ cao cấp tại Hà Nội tiếp tục là điểm sáng trong năm 2024...</p>",
    author: "Lê Văn G",
    published_at: '2024-03-09T08:26:00+07:00',
    tags: ["BấtĐộngSản", "HàNội", "CănHộCaoCấp"],
    images: [
      { url: hehe },
    ],
  },
  {
    id: 'e4f5a6b7-c8d9-4e0f-1234-567890abcdef',
    title: "Hậu sốt giá, bất động sản Hà Nội sẽ 'hẹp cửa' với nhà đầu tư nhỏ lẻ?",
    summary: "Giá bất động sản tại Hà Nội tăng mạnh, khiến nhà đầu tư nhỏ lẻ gặp khó khăn.",
    content: "<p>Sau giai đoạn sốt giá, thị trường bất động sản Hà Nội đang chứng kiến sự phân hóa...</p>",
    author: "Phạm Thị H",
    published_at: '2024-07-20T09:00:00+07:00',
    tags: ["BấtĐộngSản", "HàNội", "ĐầuTư"],
  },
  {
    id: 'f5a6b7c8-d9e0-4f12-3456-7890abcdef12',
    title: 'Thị trường bất động sản TP.HCM: Nguồn cung mới tăng mạnh',
    summary: "Thị trường bất động sản TP.HCM ghi nhận sự tăng mạnh về nguồn cung mới.",
    content: "<p>Thị trường bất động sản TP.HCM trong năm 2024 ghi nhận sự tăng trưởng mạnh mẽ...</p>",
    author: "Nguyễn Văn I",
    published_at: '2024-08-01T08:00:00+07:00',
    tags: ["BấtĐộngSản", "TPHCM", "CănHộ"],
    images: [
      { url: hello },
    ],
  },
  {
    id: 'a6b7c8d9-e0f1-2345-6789-0abcdef12345',
    title: 'TP.HCM: Giá bất động sản tăng nhẹ, giao dịch ổn định',
    summary: "Giá bất động sản tại TP.HCM tăng nhẹ trong quý II/2024.",
    content: "<p>Quý II/2024, thị trường bất động sản TP.HCM chứng kiến giá tăng nhẹ...</p>",
    author: "Trần Thị J",
    published_at: '2024-07-15T09:00:00+07:00',
    tags: ["BấtĐộngSản", "TPHCM", "GiaoDịch"],
  },
  {
    id: 'b7c8d9e0-f123-4567-890a-bcde12345678',
    title: 'Thị trường bất động sản TP.HCM: Phân khúc trung cấp hút khách',
    summary: "Phân khúc căn hộ trung cấp tại TP.HCM thu hút sự quan tâm của người mua.",
    content: "<p>Phân khúc căn hộ trung cấp tại TP.HCM đang trở thành lựa chọn hàng đầu...</p>",
    author: "Lê Văn K",
    published_at: '2024-06-20T08:00:00+07:00',
    tags: ["BấtĐộngSản", "TPHCM", "CănHộTrungCấp"],
  },
  {
    id: 'c8d9e0f1-2345-6789-0abc-de1234567890',
    title: 'Bất động sản TP.HCM: Khu Đông tiếp tục là điểm sáng',
    summary: "Khu Đông TP.HCM tiếp tục là điểm sáng của thị trường bất động sản.",
    content: "<p>Khu Đông TP.HCM, đặc biệt là TP. Thủ Đức, tiếp tục là khu vực dẫn đầu...</p>",
    author: "Phạm Thị L",
    published_at: '2024-05-30T09:00:00+07:00',
    tags: ["BấtĐộngSản", "TPHCM", "KhuĐông"],
    images: [
      { url: hello },
    ],
  },
  {
    id: 'd9e0f123-4567-890a-bcde-1234567890ab',
    title: 'TP.HCM: Thị trường bất động sản phục hồi sau đại dịch',
    summary: "Thị trường bất động sản TP.HCM phục hồi sau đại dịch.",
    content: "<p>Sau đại dịch, thị trường bất động sản TP.HCM đã phục hồi mạnh mẽ...</p>",
    author: "Nguyễn Văn M",
    published_at: '2024-04-15T08:00:00+07:00',
    tags: ["BấtĐộngSản", "TPHCM", "PhụcHồi"],
  },
  {
    id: 'e0f12345-6789-0abc-def1-234567890abc',
    title: 'Thị trường bất động sản TP.HCM: Nhà ở xã hội được quan tâm',
    summary: "Nhà ở xã hội tại TP.HCM nhận được sự quan tâm lớn từ người dân.",
    content: "<p>Nhà ở xã hội tại TP.HCM đang trở thành tâm điểm chú ý...</p>",
    author: "Trần Thị N",
    published_at: '2024-03-10T09:00:00+07:00',
    tags: ["BấtĐộngSản", "TPHCM", "NhàỞXãHội"],
  },
  {
    id: 'f1234567-890a-bcde-f123-4567890abcde',
    title: 'Becamex Tokyu bắt tay sàn BĐS đưa chuẩn sống Nhật đến Việt Nam',
    summary: "Becamex Tokyu hợp tác mang dự án MIDORI PARK The GLORY đến tay người Việt.",
    content: "<p>Dự án MIDORI PARK The GLORY của Becamex Tokyu tại Bình Dương mang phong cách sống chuẩn Nhật...</p>",
    author: "Lê Văn O",
    published_at: '2025-05-07T08:00:00+07:00',
    tags: ["BấtĐộngSản", "BìnhDương", "MIDORIPARK"],
    images: [
      { url: hi },
    ],
  },
  {
    id: '12345678-90ab-cdef-1234-567890abcdef',
    title: 'Bất động sản ven đô: Vùng trỗi dậy mới của dòng tiền đầu tư 2025',
    summary: "Bất động sản nghỉ dưỡng ven đô trở thành kênh đầu tư sáng giá.",
    content: "<p>Bất động sản ven đô đang trở thành xu hướng đầu tư mới trong năm 2025...</p>",
    author: "Phạm Thị P",
    published_at: '2025-05-07T08:00:00+07:00',
    tags: ["BấtĐộngSản", "VenĐô", "NghỉDưỡng"],
  },
  {
    id: '23456789-0abc-def1-2345-67890abcdef1',
    title: "Nhà đầu tư đổ về Khoái Châu 'ăn theo' các dự án lớn",
    summary: "Khoái Châu, Hưng Yên, trở thành điểm đến đầu tư hấp dẫn.",
    content: "<p>Khoái Châu, Hưng Yên, đang trở thành điểm đến đầu tư hấp dẫn...</p>",
    author: "Nguyễn Văn Q",
    published_at: '2025-05-07T08:00:00+07:00',
    tags: ["BấtĐộngSản", "HưngYên", "ĐầuTư"],
  },
  {
    id: '34567890-abcd-ef12-3456-7890abcdef12',
    title: "Đất nền lên ngôi trong bối cảnh mới, vùng ven 'hút' dòng tiền mạnh",
    summary: "Làn sóng đầu tư vào đất nền vùng ven Hà Nội ngày càng rõ nét.",
    content: "<p>Thông tin sáp nhập hành chính đã tạo ra làn sóng đầu tư mới...</p>",
    author: "Trần Thị R",
    published_at: '2025-05-06T21:00:00+07:00',
    tags: ["BấtĐộngSản", "HàNội", "ĐấtNền"],
    images: [
      { url: hehe },
    ],
  },
  {
    id: '4567890a-bcde-f123-4567-890abcdef123',
    title: "Vingroup, Masterise, Doji Land, Hoàng Huy... đồng loạt 'đổ bộ' Hải Phòng",
    summary: "Hải Phòng thu hút 7 dự án khu đô thị với tổng diện tích 576ha.",
    content: "<p>Hải Phòng đang trở thành điểm đến đầu tư bất động sản lớn...</p>",
    author: "Lê Văn S",
    published_at: '2025-05-06T16:39:00+07:00',
    tags: ["BấtĐộngSản", "HảiPhòng", "KhuĐôThị"],
  },
  {
    id: '567890ab-cdef-1234-5678-90abcdef1234',
    title: 'Chuyển đổi mục đích sử dụng hơn 4.100m2 đất nông nghiệp tại Bình Dương',
    summary: "Dự án A&T Saigon Riverside tại Bình Dương mang đến căn hộ cao cấp.",
    content: "<p>Dự án A&T Saigon Riverside tại Bình Dương là một trong những dự án căn hộ cao cấp...</p>",
    author: "Phạm Thị T",
    published_at: '2025-05-06T16:40:00+07:00',
    tags: ["BấtĐộngSản", "BìnhDương", "CănHộ"],
    images: [
      { url: hi },
    ],
  },
  {
    id: '67890abc-def1-2345-6789-0abcdef12345',
    title: 'Sumitomo làm khu công nghiệp gần 3.000 tỷ đồng tại Thanh Hóa',
    summary: "Khu công nghiệp Thăng Long Thanh Hóa thu hút đầu tư lớn.",
    content: "<p>Khu công nghiệp Thăng Long Thanh Hóa do tập đoàn Sumitomo đầu tư...</p>",
    author: "Nguyễn Văn U",
    published_at: '2025-05-07T08:00:00+07:00',
    tags: ["BấtĐộngSản", "ThanhHóa", "KhuCôngNghiệp"],
  },
  {
    id: '7890abcd-ef12-3456-7890-abcdef123456',
    title: 'Bình Định mời đầu tư loạt khu nghỉ dưỡng, đô thị tỷ USD',
    summary: "Bình Định thu hút gần 200 dự án bất động sản quy mô lớn.",
    content: "<p>Bình Định đang nổi lên như một điểm đến đầu tư bất động sản hấp dẫn...</p>",
    author: "Trần Thị V",
    published_at: '2025-05-07T08:00:00+07:00',
    tags: ["BấtĐộngSản", "BìnhĐịnh", "NghỉDưỡng"],
  },
  {
    id: '890abcde-f123-4567-890a-bcdef1234567',
    title: 'Vingroup dự kiến khởi công khu đô thị hơn 1.000 ha tại Long An',
    summary: "Khu đô thị Phước Vĩnh Tây tại Long An dự kiến khởi công tháng 6/2025.",
    content: "<p>Khu đô thị Phước Vĩnh Tây tại Long An, do Vingroup đầu tư...</p>",
    author: "Lê Văn W",
    published_at: '2025-05-07T08:00:00+07:00',
    tags: ["BấtĐộngSản", "LongAn", "KhuĐôThị"],
  },
];

export const postData = [
  {
    id: 'e8e616e0-d894-4936-a3f5-391682ee794c',
    title: 'Căn hộ cao cấp 3 phòng ngủ tại Cầu Giấy',
    summary: 'Căn hộ hiện đại, đầy đủ tiện nghi, vị trí trung tâm.',
    content: 'Căn hộ 75m2 tại Cầu Giấy, thiết kế sang trọng...',
    price: '3.5 tỷ VND',
    area: '75 m²',
    bedrooms: 2,
    bathrooms: 2,
    toilets: 2,
    balcony_direction: 'Đông Nam',
    frontage: '5 m',
    access_road: '6 m',
    legal_status: 'Sổ đỏ',
    furniture: 'Đầy đủ',
    floors: 1,
    house_direction: 'Đông',
    address: '123 Cầu Giấy, Hà Nội, Việt Nam',
    project_name: 'The Emerald Cầu Giấy',
    building_name: 'Tòa A',
    floor_number: 12,
    total_floors: 25,
    year_built: 2021,
    owner_name: 'Nguyễn Văn A',
    contact_phone: '0909123456',
    contact_email: 'nguyenvana@example.com',
    listed_by: 'Chính chủ',
    post_type: 'Bán căn hộ',
    view_count: 217,
    favorite_count: 35,
    is_featured: true,
    is_verified: true,
    media: [
      { type: 'image', url: hi },
      { type: 'image', url: hello },
      { type: 'video', url: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4' },
      { type: 'image', url: hehe },
    ],
  },
];
